Add support for persitent volume caims
virtualroot/charts pull request #6
Opened 2024-04-25 08:49 UTC by waok2

This PR adds support for persistent volumes claims.

2024-04-30 10:11 UTC, virtualroot requested changes
Thanks @waok2 for your work. I added a few comments.

2024-04-30 10:23 UTC, virtualroot commented on charts/structurizr/templates/pvc.yaml
> +{{- end }}
```suggestion
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.name }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
```

2024-04-30 10:24 UTC, virtualroot commented on charts/structurizr/values.yaml
> +PersistentVolumeClaim:
```suggestion
persistence:
```

2024-04-30 17:23 UTC, waok2 commented
@virtualroot I have committed the changes you requested.

2024-04-30 19:20 UTC, virtualroot approved these changes

2024-05-01 09:21 UTC, waok2 commented
@virtualroot Do we have anything that is preventing you from merging the PR?

2024-05-01 10:14 UTC, merged

2024-05-01 10:14 UTC, virtualroot commented
@waok2 merged, thanks!